### ISSUE TITLE
[Feature request] Changing logon coordinates per dimension

### ISSUE THREAD

**Issue by LukeHuckman** [awesomemoder316/PasswordLogOn#1]
Hi, nice plugin btw. I'm using this on my server right now.

However, I would like to make a request to allow the login area to be set per dimension, i.e. different login areas for the overworld and nether for example, if that is possible.

**Comment by Cloudate9** [comment]
Yeah, that's definately possible. I'll launch an update when it's done!

**Comment by Cloudate9** [comment]
This feature has been added in v1.2.0!
