### ISSUE TITLE
[Bug] Disconnecting after entering the password does insane things

### ISSUE THREAD

**Issue by Amauryeen** [awesomemoder316/PasswordLogOn#11]
**Describe the bug**
Disconnecting right after entering the password (before being teleported) does unintended things.

**To Reproduce**
1. Connect to the server
2. Enter your password
3. Disconnect one or two seconds after (before getting teleported!)
4. Reconnect

**Actual behavior**
When joining, you are already logged in on the authentication platform

**Expected behavior**
It is supposed to ask for your password and then teleport you back to your previous location

**Additional context**
Footage of the bug: https://drive.google.com/file/d/1-ibzZZBEkd9-wAC98KD0Z5sI6WwDb8qO/view?usp=sharing

**Comment by Cloudate9** [comment]
NGI, was kinda stumped on this for a bit. Realised that it was due to the player being removed from the "noPasswordEntered" Hashmap 6s after pw enter, allowing for auto removal from Hashmap if reloged in less than 6s after the password is entered. The fix will be in 1.3.1.
