### ISSUE TITLE
[Feature request] Show normal login coordinates at logs/console.

### ISSUE THREAD

**Issue by Tomauskis** [awesomemoder316/PasswordLogOn#14]
**Is your feature request related to a problem? Please describe.**
When player loggins, admins only see coordinates of the platform.

**Describe the solution you'd like**
I'd like to have an option to see normal login coordinates, as without this plugin. This should help with vanilla administrating and  maybe compatibility with other plugins.
It could look like this:

Current:
Tomauskis[/xx.xx.xxx.xx:xxxxx] logged in with entity id 189 at ([blokada]0.0, 226.0, 0.0)

Updated:
Tomauskis[/xx.xx.xxx.xx:xxxxx] logged in with entity id 189 at ([blokada]300.0, 76.0, -1000.0)

**Additional context**
I'm using this plugin for vanilla survival server.

**Comment by Cloudate9** [comment]
Sorry for not responding earlier. This is possible, and will be released as an update in a few days :D

**Comment by Tomauskis** [comment]
Thanks

**Comment by Cloudate9** [comment]
This bug/feature has been fixed in the newest update. You can get it here: [https://www.curseforge.com/minecraft/bukkit-plugins/password-log-on/files](https://www.curseforge.com/minecraft/bukkit-plugins/password-log-on/files/ )
