### ISSUE TITLE
Unauthenticated users can run commands

### ISSUE THREAD

**Issue by Amauryeen** [awesomemoder316/PasswordLogOn#5]
A player not authenticated can still use commands, which means that anyone connecting to a OP player will be able to run dangerous commands while being unauthenticated.
Having a way to avoid that would be wonderful! :)

**Comment by Cloudate9** [comment]
I can't believe that I missed out that crucial restriction! I'll make an update and post it ASAP.

**Comment by Cloudate9** [comment]
Cursoforge finally approved v1.2.1 containing the fix!
