### ISSUE TITLE
[Bug] Users with cat or wolves get their pets teleported to them when connecting

### ISSUE THREAD

**Issue by Amauryeen** [awesomemoder316/PasswordLogOn#7]
**Describe the bug**
When a user logs out while having a tamed cat or wolf, then logs in again, the cat or wolf teleports in the authentication platform, being vulnerable to damage if hit by others on the platform.

**To Reproduce**
1. Tame a cat or wolf
2. Disconnect
3. Reconnect

**Expected behavior**
The wolf or cat should remain where it is, or if not possible, the ability to hit entities while being unauthenticated should be removed, so they can not be damaged while being on the authentication platform.

**Comment by Cloudate9** [comment]
Seems like I overlooked that. Working on a fix now!

**Comment by Cloudate9** [comment]
Fixed in 1.3.0.
