### ISSUE TITLE
[Feature request] Change the messages

### ISSUE THREAD

**Issue by Amauryeen** [awesomemoder316/PasswordLogOn#8]
**Is your feature request related to a problem? Please describe.**
No. It would be nice if we could change the messages sent when joining the server or when there's an error. Having it in english can be an issue for those not speaking english.

**Describe the solution you'd like**
Allow for messages edition in a "messages.yml" file, including all texts in it.

**Comment by Cloudate9** [comment]
Sure!

**Comment by Cloudate9** [comment]
Added in 1.3.0
